### ISSUE TITLE
UNKNOWN instead of SAT for BMC benchmark

### ISSUE THREAD

**Issue by clairexen** [upscale-project/cosa2#38]
I have a benchmark that returns a witness with `btormc -kmax 25` but returns `unknown` with `cosa2 -k 25 -e bmc`.

First, I would have expected `-e bmc` to only return `sat` or `unsat`, never `unknown`. Am I missing something?

Second, is this a bug? Would there be value in making this benchmark available? (Would require some work on my side to remove some secret stuff, and I could only provide it to individual persons, not publish it here.)

**Comment by makaimann** [comment]
That would definitely be useful to provide the benchmark. It is possible that the bound differs slightly (we do some preprocessing so that the property only contains state variables). This could change the bound but only by one step. Bmc returns `sat` if there is a counterexample and `unknown` otherwise. Like the hardware model checking competition, `unsat` from `cosa2` would mean that the property holds over all time-steps.

**Comment by clairexen** [comment]
I sent the benchmark to your stanford.edu email. Let me know if there's anything else I can do to help.

**Comment by makaimann** [comment]
Great, thanks! So it turns out there's a couple things going on. 1. `btormc` solves all properties in the btor file by default, whereas `cosa2` only solves one of them. The property that is `sat` is the second one, so you'd need to run `cosa2` with the option `-p 1` to select the second property to check. 2. We do some preprocessing to make the property only over state variables. This isn't necessary for bounded model checking, but for other approaches it can be a problem to have inputs in the property. This is such a benchmark, and thus `cosa2` finds the bug at bound 26 instead of 25.

**Comment by makaimann** [comment]
Oh by the way, I should make the property index thing (and probably the potential bound mismatch) clearer for users. I'll be sure to add something to the README.

**Comment by clairexen** [comment]
Thanks for looking into this and providing that analysis.

> This is such a benchmark, and thus cosa2 finds the bug at bound 26 instead of 25.

I have a two more questions about this if I may.

1. Is there an upper bound for that extra number of cycles?

2. Are there plans to hide that within cosa2, so that cosa2 knows automatically how many cycles to add? I would assume that the current behavior is also a problem for participating in HWMCC, where (I think) bounds are given for the bmc track.

**Comment by makaimann** [comment]
No problem! There is an upper bound: it will be at most one cycle more. As for the HWMCC, that’s a good question. We didn’t have this preprocessing step for last year’s competition. I don’t know whether they take the bound into account. One simple thing we could do is start the counter at -1 or just not count the first bound in this situation (it’s known when this occurs). That’s a good idea.
